### ISSUE TITLE
Why `not_covariant` instead of `contravariant` and `invariant`?

### ISSUE THREAD

**Issue by jplatte** [Voultapher/self_cell#10]
What does `not_covariant` actually mean in this API? Does it mean contravariant or invariant? Why not just support both, with those (established) names?

**Comment by Voultapher** [comment]
2 main reasons:

A) It doesn't matter if it's invariant or contravariant, as soon as it's not covariant generating `borrow_dependent` would be unsound, see https://github.com/Voultapher/self_cell/issues/5. Plus the only thing in the language that's actually neither covariant or invariant are function parameters.

B) This crate aims to be a replacement for ouroboros in many situations. They also use this exact same binary pair of names, so migration is less confusing for users.

I'm open to improving the documentation https://docs.rs/self_cell/0.8.0/self_cell/macro.self_cell.html imo makes clear what and why these 2 options do.

**Comment by jplatte** [comment]
Okay, I see. I guess contravariance doesn't really make sense here. I still think `invariant` would be a better name than `not_covariant` though. I'll open an issue for ouroboros.

**Comment by Voultapher** [comment]
Given I don't plan on changing the name here I'll close this issue. In addition to the above reasons `invariant` is imo more confusing than helping, as really the question being asked is 'Is this type covariant?' and not 'What sort of variance does this type have?'. Plus the current two options are also easier to distinguish when visually inspecting code.
