### ISSUE TITLE
Return owner if init fails

### ISSUE THREAD

**Issue by ForsakenHarmony** [Voultapher/self_cell#12]
Seems both `rental` and `ouroboros` return the original owner back in the Error type, e.g. https://docs.rs/rental/0.5.6/rental/struct.RentalError.html, https://docs.rs/ouroboros_examples/0.9.3/ouroboros_examples/ouroboros_impl_box_and_ref/struct.BoxAndRef.html#method.try_new_or_recover

`self_cell` drops the owner on error, would it be possible to change this?

Related to https://github.com/async-email/async-imap/pull/44

**Comment by Voultapher** [comment]
I see no immediate reason why this shouldn't be possible. However I see two conflicting requirements, if we go the rental approach by changing the try constructor signatures eg. `try_from` and `try_from_fn` to include the owner we would loose out on hassle free error propagation [example](https://github.com/yeslogic/allsorts/pull/46/files#diff-de2ef9ad9a3e4bab9f70ed8338d1bec1db025522ab89526e58ae2b04afeeecdbR898) yet if we go the ourobors path of adding a new constructor type that would be increasingly at odds with stated goal of self_cell to be a minimal solution.

Initially I was reluctant to add the from_fn type constructors but the more I think about it maybe it would be more minimal if we drop the `from` and `try_from` constructor types and only rely on closures as the users of `from` can easily pass `Dependent::from` as the closure. It would be a minor loss as it doesn't enforce always creating the dependent in the same way and Clone can't automatically be implemented but I worried the current auto impl Clone behavior could easily be surprising. So maybe we cut 2 of the 4 current constructor options and add a new one `try_new_or_recover` effectively shrinking the API surface.

**Comment by Voultapher** [comment]
@ForsakenHarmony I've pushed two commits to main [1](https://github.com/Voultapher/self_cell/commit/da28deffe5925f779b424c66a53e155695f99d7d) and [2](https://github.com/Voultapher/self_cell/commit/fa9f39c771a8566ec68ecc58c5f499cb7af52de0). Please let me know if this addresses your use case.

**Comment by Voultapher** [comment]
@ForsakenHarmony friendly ping. I'll close this issue as resolved in two weeks in the absence of feedback.

**Comment by ForsakenHarmony** [comment]
@Voultapher yes, seems to work, thanks 👍

**Comment by Voultapher** [comment]
I'll publish a new version once https://github.com/Voultapher/self_cell/issues/13 is resolved.

**Comment by Voultapher** [comment]
The newly released version 0.9.0 https://github.com/Voultapher/self_cell/releases/tag/v0.9.0 contains `try_new_or_recover`.
