### ISSUE TITLE
Cannot use #[from_fn] since I update to 0.9.0

### ISSUE THREAD

**Issue by FrederickFrance** [Voultapher/self_cell#15]
Hi

I have this code and using self_cell = "0.8.0"

```
self_cell!(
    struct MyStruct1 {
        #[from_fn]
        owner: MyStruct2,

        #[covariant]
        dependent: MyEnum,
    }
);
```

Since I updated to 0.9.0 , I have, on #[from_fn] the error message : 

> no rules expected the token `#`
> 
> no rules expected this token in macro callrustc
> myfile.rs(21, 9): no rules expected this token in macro call
> no rules expected the token `#` 
> [Note] no rules expected this token in macro call

I'm still a newbie on rust and I don't find the way to change that.

**Comment by Voultapher** [comment]
The release note talks about this breaking change https://github.com/Voultapher/self_cell/releases/tag/v0.9.0. Let me know if this helps.

**Comment by FrederickFrance** [comment]
It's ok
Thank you
