### ISSUE TITLE
Performance diff vs. ouroboros

### ISSUE THREAD

**Issue by zbraniecki** [Voultapher/self_cell#2]
In Fluent we use `ouroboros` right now and I crated a draft PR to switch to `once_self_cell` because we are aiming to minimize the dependency chain - https://github.com/projectfluent/fluent-rs/pull/221

At the moment `iai` indicates that there is a perf loss in our use case with that PR:

```
iai_resolve_preferences
  Instructions:             1880367 (+0.723568%)
  L1 Accesses:              2681940 (+0.894907%)
  L2 Accesses:                 9870 (+0.162371%)
  RAM Accesses:                6532 (+0.415065%)
  Estimated Cycles:         2959910 (+0.845389%)
```

It's not a large diff, but I'm wondering if the cost is inevitable or does it indicate an opportunity for an optimization.

**Comment by zbraniecki** [comment]
To repro - `cargo criterion iai` in `./fluent-bundle`.

**Comment by Voultapher** [comment]
First of all, thank you for showing interest in this project. Curiously enough it was this discussion https://internals.rust-lang.org/t/improving-self-referential-structs/4808/74 I found when looking for a solution for self-referential structs without blowing up my dependencies and compile time that prompted me to write this library.

Unfortunately I probably won't find time until tomorrow to look closely at this.

**Comment by Voultapher** [comment]
Unless I misunderstand your use case, your dependent value can be eagerly initialized. So I suspect the extra branch and pointer walk of using `OnceCell` could be responsible here. I suggest to wait until https://github.com/Voultapher/once_self_cell/issues/1 has been implemented and then to benchmark again. After that we can start profiling if necessary. I suspect it will take a couple weeks until https://github.com/Voultapher/once_self_cell/issues/1 is implemented.

**Comment by Voultapher** [comment]
@zbraniecki I've just created #7 which among other things has 2 relevant changes that should help here:

- eagerly initialized
- single joined heap allocation instead of 2 separate ones

It's still in review and I'd be grateful for any feedback. I suggest you clone this repository checkout the `self-cell-rework` branch. Then build the documentation `cargo doc`, which a considerable amount of effort has gone into and read it to understand how you should use the `self_cell!` macro. Followed by referencing this new local version in your Fluent project. Making the necessary adjustments, for example I think you could benefit from the `try_from` option. Then benchmark and report your experience.

**Comment by Voultapher** [comment]
@zbraniecki I believe v0.7.x should be a noticeable speed up. Please run your benchmarks again and report the findings here.

**Comment by zbraniecki** [comment]
will do today!

**Comment by Voultapher** [comment]
@zbraniecki the ftml developers as mentioned saw a runtime performance improvement, please report your findings for fluent, so we can compare and hopefully further corroborate the speedup.

**Comment by Voultapher** [comment]
As part of https://github.com/projectfluent/fluent-rs/pull/227 I ran the iai benchmark and saw a slight improvement over ouroboros:

Before:

```
iai_resolve_preferences
Instructions:             1875919 (No change)
L1 Accesses:              2669397 (No change)
L2 Accesses:                 9929 (No change)
RAM Accesses:                6519 (No change)
Estimated Cycles:         2947207 (No change)
```

After:

```
iai_resolve_preferences
Instructions:             1873556 (-0.125965%)
L1 Accesses:              2667079 (-0.086836%)
L2 Accesses:                 9848 (-0.815792%)
RAM Accesses:                6516 (-0.046019%)
Estimated Cycles:         2944379 (-0.095955%)
```

**Comment by zbraniecki** [comment]
Confirmed. I think we can close this issue, thank you!
