### ISSUE TITLE
Incorrect drop order for `JoinedCell`

### ISSUE THREAD

**Issue by steffahn** [Voultapher/self_cell#20]
```rs
use self_cell::self_cell;

struct StrRef<'a>(&'a str);
impl Drop for StrRef<'_> {
    fn drop(&mut self) {
        println!("{}", self.0);
    }
}

self_cell! {
    struct Foo {
        owner: String,
        #[covariant]
        dependent: StrRef,
    }
}

fn main() {
    let foo = Foo::new("Hello World".into(), |s| StrRef(s));
} // prints garbage
```

**Comment by steffahn** [comment]
This is a soundness issue you can run into accidentally, hence yanking old versions seems absolutely necessary.

**Comment by Voultapher** [comment]
What I find surprising is how this test case https://github.com/Voultapher/self_cell/blob/5c05f54f56b83a8fd7c7ce12bbf8e401fadf4cb3/tests/self_cell.rs#L331 didn't uncover this earlier.

**Comment by Voultapher** [comment]
Also one of those things you break during refactoring https://github.com/Voultapher/self_cell/blob/cffd973b5c6a0edf48f3f924a5019971403640f0/src/unsafe_once_self_cell.rs#L76 sigh

**Comment by Voultapher** [comment]
Regardless, thanks for reporting and fixing the bug!

**Comment by steffahn** [comment]
Why not a point release of v0.9? This way users of 0.9.* don’t break; it’s a bugfix, so technically not really a breaking change, right?

<hr>

> What I find surprising is how this test case
> 
> https://github.com/Voultapher/self_cell/blob/5c05f54f56b83a8fd7c7ce12bbf8e401fadf4cb3/tests/self_cell.rs#L331
> 
> didn't uncover this earlier.

I’m not entirely sure; indeed even `MIRIFLAGS="-Zmiri-track-raw-pointers" cargo +nightly miri test` doesn’t seem to complain though. Maybe the code is UB, maybe it’s not – what’s certainly a problem is that the `Option<Vec<…>>` is a `None` value, so dropping the owner doesn’t really do anything in practice.

<hr>

Looking at https://crates.io/crates/self_cell/reverse_dependencies, opening a PR to https://crates.io/crates/bracket might be a reasonable idea (since they’re the only crates.io crate using `self_cell` below `0.9.*`). Still assuming a 0.9.3 release instead of 0.10 – otherwise *all* reverse dependencies would need to be updated.

<hr>

I’ve never done such a thing, but maybe this broken drop order is a reasonable addition to https://rustsec.org/ as well.

**Comment by Voultapher** [comment]
Regarding rustsec, never having done such a thing myself either, I wonder how applicable it is. I would assume that in practice it only shows up if a programmer writes code in certain way, not via malicious input. And given how relatively small this project still is. But I'm open to the idea.
