### ISSUE TITLE
Memory leaks when destructors panic

### ISSUE THREAD

**Issue by steffahn** [Voultapher/self_cell#26]
For more info see the branch I’ve already mentioned in #24, i.e.
[steffahn/self_cell@`fix_drop_order...fix_double_free_and_leaks`](https://github.com/Voultapher/self_cell/compare/ebbf355...c482860#diff-1778ecc1b76a790dccfe3d31d658c07d2464493912a0e873cce3cdf1a361f8d7R810-R854)
in particular, the highlighted test cases.

(FYI, that branch currently also contains #25)

These memory leaks are not a soundness issue; still, fixing the problem is a nice-to-have improvement.

I can rebase, resolve merge conflicts, and open a PR once #21 and #25 are merged.

**Comment by Voultapher** [comment]
panic in Drop needs some getting used to when coming from the noexcept C++ world.

**Comment by Voultapher** [comment]
I wonder if ouroboros has the same issue.
