### ISSUE TITLE
Use of addr_of_mut requires recent Rust

### ISSUE THREAD

**Issue by mitsuhiko** [Voultapher/self_cell#30]
I got a pull request sent for the new yank which I very much appreciate (https://github.com/mitsuhiko/minijinja/pull/21). However the latest version uses `addr_of_mut!` which bumps up the rustc requirement to 1.51. I was previously able to target `1.42` which I need for an upstream user of this crate.

Would it be possible to restore support for 1.42 somehow?

**Comment by Voultapher** [comment]
I've just published https://github.com/Voultapher/self_cell/releases/tag/v0.10.1 I hope that works for mininjinja.
