### ISSUE TITLE
Update the comparison to Ourouboros in the README

### ISSUE THREAD

**Issue by Shnatsel** [Voultapher/self_cell#40]
Ourouboros has a fundamental soundness problem acknowledged by the author, and the author recommends using `self_cell` in place of ourouboros.

https://github.com/joshua-maros/ouroboros/issues/88

**Comment by Voultapher** [comment]
Thanks for the heads-up, I created a PR https://github.com/Voultapher/self_cell/pull/41 that changes that section. Please let me know if this fixes this issue. Also I'm glad [that I didn't assume 'static lifetime replacement is a valid way to store the value](https://github.com/Voultapher/self_cell/blob/e064648b951dc8f1a595cf49ce629debf6bb8345/src/lib.rs#L347-L350).
