### ISSUE TITLE
comparison with selfref

### ISSUE THREAD

**Issue by SoniEx2** [Voultapher/self_cell#45]
selfref requires more recent rustc but supports more lifetime complexity akin to that of ouroboros, as well as no-alloc environments.

thoughts?

**Comment by Voultapher** [comment]
I took a look and here are some thoughts:

- I found the documentation quite confusing. It mixes what is possible and what isn't under the same names, while omitting code in the later code blocks without specifying from which block above it expects parts. It also fails to establish why anyone would want to use such a crate. The examples do nothing other than constructing types, no words about interfaces etc.

- The usage is quite awkward and cumbersome. From what I can tell the user always has to use `Cell` or `RefCell` + `Option` for the dependent value. Making access and construction cumbersome. In addition the only allowed access pattern is via `operate_in` which creates the known closure pyramid problem and is generally incompatible with a lot of programming patterns.

- The various wrapper types, `Box`, `Pin`, `Holder`, `OperateIn`, `MyTypeKey` etc. adds a lot of cognitive load. And make signatures complex.

- The documentation claims:

> Further, this is the only crate for self-referential types which supports additional lifetimes than the self-referential one

That's false. Both ouroboros and self_cell support owners with lifetimes.

- Overall I don't understand the point of no-alloc environment support. The one use case I can think of for self-referential types is building abstractions that encapsulate some modification where the result is a processed new value, where constructing the dependent value is expensive and we want to only do it once borrowing the local stack value. For example https://docs.rs/self_cell/1.0.1/self_cell/#a-motivating-use-case. This requires returning the value from a function, which in turn means the value must be movable. With selfref you can construct a self-referential type with `pin!`, but you won't be able to return that from a function, completely nullifying the whole point of having the self-referential type. The only exception I can think of is the async generator stuff, but I'm not familiar with the specifics.

I hope that helps.

**Comment by SoniEx2** [comment]
self_cell supports owners with lifetimes?

... oh right, self_cell doesn't support dependents with lifetimes. and ouroboros is proc macro hell. so you can't e.g. represent hexchat internal state using self_cell. we think we also had some trouble getting the lifetimes to work properly with ouroboros, particularly [it doesn't allow enough layout control](https://github.com/joshua-maros/ouroboros/issues/74).

hexchat is a C program which uses a lot of structs with linked lists with backreferences. our goal was to figure out whether we could represent those safely, including the nested backreferences. as a bonus we also wanted `?Sized` support for another project. we like to think it turned out very well.

we also have the `broption` crate to make access easier, it's fairly efficient even if it doesn't work quite how we wanted it to. nevertheless, some kind of `Cell` is required for soundness, tho the `LCell` compatibility module/feature enables additional use-cases not covered by the main crate, because we found that we really needed those use-cases.

and honestly, boilerplate is a small price to pay for the flexibility selfref gives you. we'd love to reduce boilerplate, but all these safety wrappers are used for soundness, so there should be another way than dismissing the safety wrappers entirely.
