### ISSUE TITLE
with_dependent_mut() missing to impl next() on self-referential iterator

### ISSUE THREAD

**Issue by hniksic** [Voultapher/self_cell#56]
I stumbled upon a (seemingly) easy  self-referential use case for which I wanted to use self-cell because I really dislike the huge amounts of code that ouroboros generates - but I got stuck fairly quickly. 

The use case I stumbled on is that of creating an owned version of `split_whitespace()` which uses `split_whitespace()` internally. That requires self-referencing (if it is to reuse `str::split_whitespace()` because the iterator must contain both the owned string and the `SplitWhitespace<'a>` that iterates over it. What I had in mind was something like:

```rust
fn owned_split(s: String) -> impl Iterator<Item = String> {
    self_cell::self_cell! {
        struct OwnedSplit {
            owner: String,
            #[not_covariant]
            dependent: SplitWhitespace,
        }
    }
    impl Iterator for OwnedSplit {
        type Item = String;
        fn next(&mut self) -> Option<String> {
            self.with_dependent(|_, split| split.next().map(|s| s.to_owned())) // XXX can't call next() on shared reference
        }
    }
    OwnedSplit::new(s, |s| s.split_whitespace())
}
```

...but it obviously doesn't compile because `borrow_dependent()` gives out a shared reference on which I can't call `next()`. In ouroboros the example compiles as:

```rust
fn owned_split(s: String) -> impl Iterator<Item = String> {
    #[self_referencing]
    struct OwnedSplit {
        owner: String,
        #[borrows(owner)]
        #[not_covariant]
        split: SplitWhitespace<'this>,
    }
    impl Iterator for OwnedSplit {
        type Item = String;
        fn next(&mut self) -> Option<String> {
            self.with_split_mut(|split| split.next().map(|s| s.to_owned()))
        }
    }
    OwnedSplit::new(s, |s| s.split_whitespace())
}
```

Is this use case covered by `self-cell` and if so, how does one go about it?

**Comment by hniksic** [comment]
Ah, I just figured out I can simply use a `RefCell`. I guess that's the recommended way to do it?

**Comment by Voultapher** [comment]
Hi, thanks for reaching out. I have to say I'm a little confused by this request. `self_cell` does provide a `with_dependent_mut` method as documented here https://docs.rs/self_cell/latest/self_cell/macro.self_cell.html. Based on the code example it's not clear to me why that wouldn't work here.

**Comment by hniksic** [comment]
Indeed, it does, thanks for pointing it out. I think I got confused by looking at the [top-level page](https://docs.rs/self_cell/latest/self_cell/) where `mut` is not mentioned at all, so I assumed it doesn't exist. It's only after writing the ouroboros version that I figured the value should be non-covariant and switched from `borrow_dependent()` to `with_dependent()`, without realizing that the latter has a mut variant. Another thing that threw me off was that I clicked through the three advanced examples, and since none of them sported mutability, I assumed it wasn't provided.

**Comment by Voultapher** [comment]
Good point, the top-level documentation can be confusing. I've juste pushed https://github.com/Voultapher/self_cell/commit/53d2878ddd163bef01ffa9d3fde2bdd417a21fea, please let me know if that makes it more clear.

**Comment by hniksic** [comment]
Thanks, the change is simple and very effective, the new phrasing would certainly have helped me learn of `with_dependent_mut()`!

**Comment by hniksic** [comment]
Here is the StackOverflow answer where I needed this, and which I've now switched to `self_cell`: https://stackoverflow.com/a/78417749/1600898

I sometimes feel there is a lack of clear and concise examples of how to use self-referential crates. The [most linked-to SO question on the topic](https://stackoverflow.com/questions/32300132/why-cant-i-store-a-value-and-a-reference-to-that-value-in-the-same-struct) is especially egregious for not providing a clear guidance on how to do it, which ends up in people imagining it's much harder than it really is. (I [blogged](https://morestina.net/blog/1868/self-referential-types-for-fun-and-profit) about the same topic in the past.)

**Comment by hniksic** [comment]
I wonder if it might make sense to create a trait with methods like `with_dependent()` and `borrow_dependent()`, which the macro would implement. It might help with writing generic code, and the trait provide a good place to document which generated methods exist and what they do. The macro could still generate inherent methods for backward compatibility (and convenience).

**Comment by Voultapher** [comment]
> I wonder if it might make sense to create a trait with methods like with_dependent() and borrow_dependent(), which the macro would implement. It might help with writing generic code, and the trait provide a good place to document which generated methods exist and what they do. The macro could still generate inherent methods for backward compatibility (and convenience).

I don't see how that would be possible. The whole reason why this is a macro and not a classical type and or traits is that there is no way to abstract over lifetime in the way we need. You can't pass a type without its lifetimes, that's why this crate and similar ones resort to using macro-rules `$ident` to abstract over it. Because it allows a function signature like `fn borrow_dependent<'a>(&'a self) -> &'a $Dependent<'a>`.

**Comment by Voultapher** [comment]
I've published version 1.0.4 that contains the documentation improvements. Closing this issue now.

**Comment by hniksic** [comment]
Thanks for the documentation improvements!

>The whole reason why this is a macro and not a classical type and or traits is that there is no way to abstract over lifetime in the way we need. You can't pass a type without its lifetimes, that's why this crate and similar ones resort to using macro-rules `$ident` to abstract over it. Because it allows a function signature like `fn borrow_dependent<'a>(&'a self) -> &'a $Dependent<'a>`.

Just to clarify in case it wasn't clear already, I didn't suggest to replace the macro with a blanket implementation of a trait or something like that, I understand that's impossible. I proposed a trait useful mostly for documentation purposes, with the macro filling in the implementation. With GATs at least the signatures of `borrow_dependent()` and `with_dependent()` appear expressible, e.g. this compiles:

```rust
trait SelfCell {
    type Owner;
    type Dependent<'a> where Self: 'a;

    fn borrow_dependent<'a>(&'a self) -> &'a Self::Dependent<'a>;
    fn with_dependent<'outer_fn, Ret>(
        &'outer_fn self,
        func: impl for<'a> FnOnce(&'a Self::Owner, &'outer_fn Self::Dependent<'a>) -> Ret,
    ) -> Ret;
    // ...
}
```

For a given type `$t` the macro could generate `impl $crate::SelfCell for $t`, with the generated methods just calling the inherent methods of the same name (generated by the macro as they are now).

Doing this might be more trouble than it's worth, but superficially it seems like it should be possible with GATs.

**Comment by hniksic** [comment]
That makes sense - but I assume the MSRV will be bumped at some point? Would you entertain the idea at a later time, or do you think it doesn't pull its weight regardless? If it's the latter, I'll let it rest to avoid wasting time.

**Comment by Voultapher** [comment]
My gut feeling is it doesn't pull its weight. I will bump the MSRV when I see a strong need for it.
